import React, { useState } from 'react';
import { Bot, ShieldCheck, HelpCircle, AlertTriangle, Copy, Check } from 'lucide-react';

export const AnswerCard = ({ answer, grounded, groundingDetails, mockMode }) => {
  const [copied, setCopied] = useState(false);

  if (!answer) return null;

  const isGrounded = grounded === true;
  const isRefusal = answer.includes("couldn't find") || answer.includes("Refusal");

  const handleCopy = () => {
    navigator.clipboard.writeText(answer);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="glass-panel glass-panel-glow rounded-3xl p-6 md:p-8 border border-slate-800 shadow-2xl relative overflow-hidden">
      {/* Top Bar Header */}
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center gap-2.5">
          <div className="p-2 rounded-xl bg-indigo-500/10 border border-indigo-500/20 text-indigo-400">
            <Bot className="w-5 h-5" />
          </div>
          <div>
            <h3 className="text-lg font-bold text-white">Synthesized RAG Answer</h3>
            <p className="text-xs text-slate-400">Generated by Sarvam-105B LLM grounded on MSMARCO context</p>
          </div>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={handleCopy}
            className="p-2 rounded-xl bg-slate-800/80 hover:bg-slate-700 text-slate-300 transition-all text-xs flex items-center gap-1.5 border border-slate-700/80"
            title="Copy answer text"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
            <span>{copied ? 'Copied!' : 'Copy'}</span>
          </button>

          <div className={`flex items-center gap-1.5 px-3.5 py-1.5 rounded-full text-xs font-bold uppercase tracking-wider ${
            isRefusal ? 'bg-amber-500/20 text-amber-300 border border-amber-500/40 badge-glow-amber' :
            isGrounded ? 'bg-emerald-500/20 text-emerald-300 border border-emerald-500/40 badge-glow-emerald' :
            'bg-rose-500/20 text-rose-300 border border-rose-500/40'
          }`}>
            {isRefusal ? (
              <>
                <HelpCircle className="w-4 h-4 text-amber-400" />
                <span>Context Refusal</span>
              </>
            ) : isGrounded ? (
              <>
                <ShieldCheck className="w-4 h-4 text-emerald-400" />
                <span>Grounded in Dataset</span>
              </>
            ) : (
              <>
                <AlertTriangle className="w-4 h-4 text-rose-400" />
                <span>General Knowledge</span>
              </>
            )}
          </div>
        </div>
      </div>

      {/* Answer Main Text Box */}
      <div className="bg-slate-950/80 p-6 rounded-2xl border border-slate-800/90 text-slate-100 text-base leading-relaxed font-normal shadow-inner relative">
        <p className="whitespace-pre-wrap">{answer}</p>
      </div>

      {/* Grounding Metadata Footer */}
      {groundingDetails && (
        <div className="mt-4 flex flex-col md:flex-row items-start md:items-center justify-between text-xs text-slate-400 gap-2 bg-slate-900/60 p-3 rounded-xl border border-slate-800/60">
          <div className="flex items-center gap-2">
            <span className="w-2 h-2 rounded-full bg-indigo-400"></span>
            <span>Grounding Validator: <strong className="text-slate-200">{groundingDetails.reason}</strong></span>
          </div>
          {groundingDetails.confidence !== null && groundingDetails.confidence !== undefined && (
            <div className="font-mono text-emerald-400 font-bold bg-emerald-950/60 border border-emerald-800/60 px-2.5 py-0.5 rounded-lg">
              Confidence Score: {(groundingDetails.confidence * 100).toFixed(0)}%
            </div>
          )}
        </div>
      )}
    </div>
  );
};
